#' Add protein lengths from fasta file to data frame (id_col - protein id column.)
#' @rdname saintExpress
#' @param intdata data.frame
#' @param fasta list of sequences created with \code{\link[seqinr]{read.fasta}}
#' @param id_col column with protein ids/accessions.
#' @return `intdata` with an added `protein.length` column.
#' @export
#' @examples
#' add_protein_lengths(
#'   data.frame(protein_Id = "P1"),
#'   list(P1 = "MPEPTIDE")
#' )
#'
add_protein_lengths <- function(
  intdata,
  fasta,
  id_col = "protein_Id"
) {
  plengths <- data.frame(
    id = names(fasta),
    protein.length = vapply(fasta, stringr::str_length, integer(1))
  )
  byx <- "id"
  names(byx) <- id_col
  intdata <- dplyr::left_join(intdata, plengths, by = byx)
  intdata$protein.length[is.na(intdata$protein.length)] <- as.integer(mean(
    intdata$protein.length,
    na.rm = TRUE
  ))
  return(intdata)
}

#' Convert tidy table with protein quants into SaintExpress compatible inputs
#' @param xx data.frame in long format
#' @export
#' @rdname saintExpress
#' @param quantcolumn intensity column
#' @param proteinID protein accession
#' @param geneNames column with gene names
#' @param proteinLength column with protein lengths
#' @param IP_name raw.file
#' @param baitCol column with bait definition (condition)
#' @param CorTCol is it control or TRUE (SaintExpress speach)
#' @return named list with `inter`, `prey`, and `bait` SAINT input tables.
#' @examples
#'
#' bb <- prolfqua::prolfqua_data('data_IonstarProtein_subsetNorm')
#' bb$config <- bb$config$clone(deep = TRUE)
#' xx <- prolfqua::LFQData$new(bb$data, bb$config)
#' exampleDat <- xx$data_long() |>
#'   dplyr::mutate(CorT = dplyr::case_when(dilution. == "a" ~ "C", TRUE ~ "T"))
#' # sample protein lengths
#'
#' tmp <- data.frame(protein_Id = unique(exampleDat$protein_Id))
#' tmp$proteinLength <- as.integer(runif(nrow(tmp), min = 150, max = 2500))
#' exampleDat <- dplyr::inner_join(tmp, exampleDat)
#' res <- protein_2localSaint(exampleDat,quantcolumn = "medpolish",
#'                    proteinID = "protein_Id",
#'                    proteinLength = "proteinLength",
#'                    IP_name = "raw.file",
#'                    baitCol = "dilution.",
#'                    CorTCol = "CorT"
#'                    )
#'
#' stopifnot(names(res) == c( "inter", "prey",  "bait"))
#'
protein_2localSaint <- function(
  xx,
  quantcolumn = "mq.protein.intensity",
  proteinID = "protein_Id",
  geneNames = proteinID,
  proteinLength = "protein.length",
  IP_name = "raw.file",
  baitCol = "bait",
  CorTCol = "CorT"
) {
  reqcolumns <- c(
    quantcolumn,
    proteinID,
    geneNames,
    proteinLength,
    IP_name,
    baitCol,
    CorTCol
  )
  if (!all(reqcolumns %in% colnames(xx))) {
    missing_columns <- reqcolumns[which(!reqcolumns %in% colnames(xx))]
    stop(
      "columns not found ",
      toString(missing_columns)
    )
  }
  res <- list()
  bait <- xx |> dplyr::select(!!!rlang::syms(c(IP_name, baitCol, CorTCol)))
  bait <- dplyr::distinct(bait)
  res$bait <- bait
  prey <- xx |>
    dplyr::select(
      proteinID = !!rlang::sym(proteinID),
      proteinLength = !!rlang::sym(proteinLength),
      geneNames = !!rlang::sym(geneNames)
    )
  prey <- dplyr::distinct(prey)
  res$prey <- prey
  inter <- xx |>
    dplyr::select(
      !!!rlang::syms(c(IP_name, baitCol, proteinID, quantcolumn))
    ) |>
    dplyr::filter(!!rlang::sym(quantcolumn) > 0)
  res$inter <- inter
  res <- res[c("inter", "prey", "bait")]
  return(res)
}


#' Run SAINTexpress analysis
#'
#' Executes SAINTexpress on prepared input data. Delegates to the
#' \pkg{saintexpressbin} package for the native binary / Docker engine, and to
#' the \pkg{saintexpress} package for the pure-R engine. If `engine = "binary"`
#' is requested but \pkg{saintexpressbin} is not installed, a warning is issued
#' and the call falls back to the R engine.
#'
#' @export
#' @rdname saintExpress
#' @param si output of protein_2localSaint function
#' @param filedir where to store the saint express inputs
#' @param spc if TRUE spectral counts, if FALSE intensities (see SAINTexpress documentation)
#' @param CLEANUP TRUE remove all files generated by SAINTexpress
#' @param use_docker logical or NULL. NULL (default) uses a native executable
#'   when available and falls back to Docker on macOS. TRUE forces Docker.
#'   FALSE forces native execution.
#' @param engine execution engine. \code{"binary"} runs bundled SAINTexpress
#'   via \pkg{saintexpressbin}; \code{"r"} runs the R implementation via
#'   \pkg{saintexpress}.
#' @param optimizer optimizer for \code{engine = "r"}. \code{"base"} uses
#'   \code{\link[stats]{optim}}; \code{"nloptr"} uses NLopt COBYLA when
#'   \pkg{nloptr} is installed.
#' @return list with SAINTexpress `listFile`, parsed `list`, and run `out`.
runSaint <- function(
  si,
  filedir = getwd(),
  spc = TRUE,
  CLEANUP = TRUE,
  use_docker = NULL,
  engine = c("binary", "r"),
  optimizer = c("base", "nloptr")
) {
  stopifnot(names(si) == c("inter", "prey", "bait"))
  engine <- match.arg(engine)
  optimizer <- match.arg(optimizer)

  if (engine == "binary" && !requireNamespace("saintexpressbin", quietly = TRUE)) {
    warning(
      "engine = 'binary' requires the 'saintexpressbin' package, which is not installed. ",
      "Falling back to engine = 'r'."
    )
    engine <- "r"
  }

  if (engine == "r") {
    type <- if (isTRUE(spc)) "spc" else "int"
    res <- saintexpress::run_saint(si, mode = type, optimizer = optimizer)
    implementation <- if (type == "spc") "spectral-count" else "intensity"
    return(list(
      listFile = data.frame(listFile = NA_character_),
      list = res,
      out = data.frame(
        out = paste("R SAINTexpress", implementation, "implementation")
      )
    ))
  }

  type <- if (isTRUE(spc)) "spc" else "int"
  saintexpressbin::saintexpress_run(
    si,
    type = type,
    workdir = filedir,
    cleanup = CLEANUP,
    use_docker = use_docker
  )
}
